2023-05-02 14:54:25,345 Starting bot_main
2023-05-02 14:54:25,350 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<check_message() done, defined at E:\PyCharm Community Edition 2022.3\wireguardBot\bot_main\wireguardBot\bot.py:251> exception=IntegrityError('UNIQUE constraint failed: account.id')>
Traceback (most recent call last):
  File "E:\PyCharm Community Edition 2022.3\wireguardBot\bot_main\wireguardBot\bot.py", line 253, in check_message
    await check.check_balance(bot)
  File "E:\PyCharm Community Edition 2022.3\wireguardBot\bot_main\wireguardBot\app\check_balance.py", line 65, in check_balance
    db.add_or_update_user(user['id'], amount=int(user['amount']) - DAY_PAY)
  File "E:\PyCharm Community Edition 2022.3\wireguardBot\bot_main\wireguardBot\database.py", line 23, in add_or_update_user
    cursor.execute(statement, {
sqlite3.IntegrityError: UNIQUE constraint failed: account.id
2023-05-02 14:54:25,577 Bot: TestBot [@tralala159159_bot]
2023-05-02 14:54:25,725 Updates were skipped successfully.
2023-05-02 14:54:25,726 Start polling.
2023-05-02 14:54:54,218 Stop polling...
2023-05-02 14:54:54,219 Goodbye!
